git actions test 1

diff --git a/.github/workflows/learn-github-actions.yml b/.github/workflows/learn-github-actions.yml
--- a/.github/workflows/learn-github-actions.yml
+++ b/.github/workflows/learn-github-actions.yml
@@ -1,111 +1,70 @@
-name: Check work log
+name: Check package version
 
 run-name: ${{github.repository}} is running
 
 on:
-  push:
+  pull_request:
     branches:
-      - '**' # 모든 브랜치 적용
+      - 'test2'
 
 jobs:
-  check-work-log-file:
+  check-package-version:
     if: github.repository == 'inseong01/inseong01'
     runs-on: ubuntu-latest
 
     steps:
-      - name: Run current-date-time@v1
-        id: t1
-        uses: Kaven-Universe/github-action-current-date-time@v1
-        with:
-          format: 'YYYY.MM.DD.'
-          timezone-offset: -540
-
-      - name: Setup current date
-        run: |
-          YEAR_SHORT=$(echo "${{ steps.t1.outputs.year }}" | cut -c3-4)
-          MONTH=$(expr ${{ steps.t1.outputs.month }} + 0)
-          DAY=$(expr ${{ steps.t1.outputs.day }} + 0)
-
-          echo "CURRENT_DATE=$YEAR_SHORT.$MONTH.$DAY." >> $GITHUB_ENV
-          echo "CURRENT_DATE: $YEAR_SHORT.$MONTH.$DAY."
-
-      - name: Checkout repository
+      - name: Checkout Head
         uses: actions/checkout@v3
 
-      - name: Find work log txt file
-        run: |
-          FILE_PATH=$(find . -type f -name "작업일지.txt" | head -n 1)
-          COMMIT_HASH=$(git log -n 1 --pretty=format:"%H" "$FILE_PATH")
-
-          echo "WORK_LOG_FILE: $FILE_PATH"
-          echo "COMMIT_HASH: $COMMIT_HASH"
-
-          if [ -f "$FILE_PATH" ]; then
-            echo "WORK_LOG_FILE=$FILE_PATH" >> $GITHUB_ENV
-            echo "WORK_LOG_FILE was found."
-          else
-            echo "Error: Could not find WORK_LOG_FILE."
-            exit 1
-          fi
-
-      - name: Check current date work log
-        run: |
-          if grep -q "$CURRENT_DATE" "$WORK_LOG_FILE"; then
-            echo "Work log was written."
-          else 
-            echo "Error: Work log was not written."
-            echo "Check the work log from 작업일지.txt"
-            echo "CURRENT_DATE is $CURRENT_DATE"
-            exit 1
-          fi
-
-  check-package-version:
-    if: github.repository == 'inseong01/inseong01' && github.base_ref == 'main' && !github.event.before
-    runs-on: ubuntu-latest
-
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v3
-
-      - name: Find package.json
+      - name: Get file in Head branch
+        env:
+          GH_TOKEN: ${{ github.token }}
         run: |
           FILE_PATH=$(find . -type f -name "package.json" | head -n 1)
-          COMMIT_HASH=$(git log -n 1 --pretty=format:"%H" "$FILE_PATH")
 
-          echo "FILE_PATH: $FILE_PATH"
-          echo "COMMIT_HASH: $COMMIT_HASH"
-
-          if [ -f FILE_PATH ]; then
-            echo "CURRENT_PACKAGE_JSON=$FILE_PATH" >> $GITHUB_ENV
-            echo "FILE_PATH was found"
-          else 
-            echo "Error: FILE_PATH was not found"
+          if [ -z "$FILE_PATH" ]; then
+            echo "File doesn't exist"
             exit 1
           fi
 
-      - name: Checkout previous commit
-        run: |
-          # 이전 package.json 버전 확인
-          git checkout HEAD~1
+          echo "FILE_PATH: $FILE_PATH"
+          echo "HEAD_PACKAGE_JSON_PATH=$FILE_PATH" >> $GITHUB_ENV
+          echo "Succeeded"
 
-      - name: Find package.json
+      - name: Checkout Base
+        env:
+          BASE_REF: ${{ github.base_ref }} # 기준 브랜치
+        run: |
+          git fetch origin $BASE_SHA:$BASE_SHA || git fetch origin $BASE_SHA
+          git checkout $BASE_SHA
+
+          echo "BASE_REF: $BASE_REF"
+
+      - name: Get file in the Base branch
         run: |
           FILE_PATH=$(find . -type f -name "package.json" | head -n 1)
-          COMMIT_HASH=$(git log -n 1 --pretty=format:"%H" "$FILE_PATH")
 
-          echo "FILE_PATH: $FILE_PATH"
-          echo "COMMIT_HASH: $COMMIT_HASH"
-
-          if [ -f FILE_PATH ]; then
-            echo "PREV_PACKAGE_JSON=$FILE_PATH" >> $GITHUB_ENV
-            echo "FILE_PATH was found"
-          else 
-            echo "Error: FILE_PATH was not found"
+          if [ -z "$FILE_PATH" ]; then
+            echo "File doesn't exist"
             exit 1
           fi
 
-      - name: Compare package.json version
-        run: |
-          # 변수 작성
+          echo "FILE_PATH: $FILE_PATH"
+          echo "BASE_PACKAGE_JSON_PATH=$FILE_PATH" >> $GITHUB_ENV
+          echo "Succeeded"
 
-          # 이전보다 버전 낮거나 동일하면 실패
+      - name: Compare file version
+        run: |
+          CUR_VERSION=$(jq -r '.version' $BASE_PACKAGE_JSON_PATH)
+          PREV_VERSION=$(jq -r '.version' $HEAD_PACKAGE_JSON_PATH)
+
+          echo "CUR_VERSION: $CUR_VERSION"
+          echo "PREV_VERSION: $PREV_VERSION"
+
+          if  [[ "$(printf '%s\n%s' "$PREV_VERSION" "$CUR_VERSION" | sort -V | head -n 1 )" == "$CUR_VERSION" ]]; then
+            echo "Error: Check current package.json version"
+            echo "Current version is not greater than previous version"
+            exit 1
+          fi
+
+          echo "Succeeded"
