create: git actions first test
- '작업일지.txt' 작성 확인 테스트 작성

diff --git a/.github/workflows/learn-github-actions.yml b/.github/workflows/learn-github-actions.yml
--- a/.github/workflows/learn-github-actions.yml
+++ b/.github/workflows/learn-github-actions.yml
@@ -1,58 +1,111 @@
 name: Check work log
 
-on:
-  workflow_dispatch:
+run-name: ${{github.repository}} is running
 
+on:
   push:
     branches:
       - '**' # 모든 브랜치 적용
-    paths:
-      - '**/*.md'
 
 jobs:
   check-work-log-file:
-    if: github.repository == 'inseong/profile'
+    if: github.repository == 'inseong01/inseong01'
     runs-on: ubuntu-latest
 
     steps:
-      - name: Get current date 1
+      - name: Run current-date-time@v1
         id: t1
         uses: Kaven-Universe/github-action-current-date-time@v1
         with:
-          format: 'YY_MM_DD'
+          format: 'YYYY.MM.DD.'
           timezone-offset: -540
 
-      - name: Output 1
+      - name: Setup current date
         run: |
-          echo "The time was ${{ steps.t1.outputs.time }}"
-          echo "The year was ${{ steps.t1.outputs.year }}"
-          echo "The month was ${{ steps.t1.outputs.month }}"
-          echo "The day was ${{ steps.t1.outputs.day }}"
+          YEAR_SHORT=$(echo "${{ steps.t1.outputs.year }}" | cut -c3-4)
+          MONTH=$(expr ${{ steps.t1.outputs.month }} + 0)
+          DAY=$(expr ${{ steps.t1.outputs.day }} + 0)
 
-      - name: Get current date 2 (KST, UTC+9)
-        id: t2
-        uses: Kaven-Universe/github-action-current-date-time@v1
-        with:
-          format: 'YY_MM_DD'
-          timezone-offset: -540
+          echo "CURRENT_DATE=$YEAR_SHORT.$MONTH.$DAY." >> $GITHUB_ENV
+          echo "CURRENT_DATE: $YEAR_SHORT.$MONTH.$DAY."
 
-      - name: Output 2
+      - name: Checkout repository
+        uses: actions/checkout@v3
+
+      - name: Find work log txt file
         run: |
-          echo "The time was ${{ steps.t2.outputs.time }}"
-          echo "The year was ${{ steps.t2.outputs.year }}"
-          echo "The month was ${{ steps.t2.outputs.month }}"
-          echo "The day was ${{ steps.t2.outputs.day }}"
+          FILE_PATH=$(find . -type f -name "작업일지.txt" | head -n 1)
+          COMMIT_HASH=$(git log -n 1 --pretty=format:"%H" "$FILE_PATH")
 
-      - name: Get current date 3 (KST, UTC+9, Full Year)
-        id: t3
-        uses: Kaven-Universe/github-action-current-date-time@v1
-        with:
-          format: 'YYYY_MM_DD'
-          timezone-offset: -540
+          echo "WORK_LOG_FILE: $FILE_PATH"
+          echo "COMMIT_HASH: $COMMIT_HASH"
 
-      - name: Output 3
+          if [ -f "$FILE_PATH" ]; then
+            echo "WORK_LOG_FILE=$FILE_PATH" >> $GITHUB_ENV
+            echo "WORK_LOG_FILE was found."
+          else
+            echo "Error: Could not find WORK_LOG_FILE."
+            exit 1
+          fi
+
+      - name: Check current date work log
         run: |
-          echo "The time was ${{ steps.t3.outputs.time }}"
-          echo "The year was ${{ steps.t3.outputs.year }}"
-          echo "The month was ${{ steps.t3.outputs.month }}"
-          echo "The day was ${{ steps.t3.outputs.day }}"
+          if grep -q "$CURRENT_DATE" "$WORK_LOG_FILE"; then
+            echo "Work log was written."
+          else 
+            echo "Error: Work log was not written."
+            echo "Check the work log from 작업일지.txt"
+            echo "CURRENT_DATE is $CURRENT_DATE"
+            exit 1
+          fi
+
+  check-package-version:
+    if: github.repository == 'inseong01/inseong01' && github.base_ref == 'main' && !github.event.before
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v3
+
+      - name: Find package.json
+        run: |
+          FILE_PATH=$(find . -type f -name "package.json" | head -n 1)
+          COMMIT_HASH=$(git log -n 1 --pretty=format:"%H" "$FILE_PATH")
+
+          echo "FILE_PATH: $FILE_PATH"
+          echo "COMMIT_HASH: $COMMIT_HASH"
+
+          if [ -f FILE_PATH ]; then
+            echo "CURRENT_PACKAGE_JSON=$FILE_PATH" >> $GITHUB_ENV
+            echo "FILE_PATH was found"
+          else 
+            echo "Error: FILE_PATH was not found"
+            exit 1
+          fi
+
+      - name: Checkout previous commit
+        run: |
+          # 이전 package.json 버전 확인
+          git checkout HEAD~1
+
+      - name: Find package.json
+        run: |
+          FILE_PATH=$(find . -type f -name "package.json" | head -n 1)
+          COMMIT_HASH=$(git log -n 1 --pretty=format:"%H" "$FILE_PATH")
+
+          echo "FILE_PATH: $FILE_PATH"
+          echo "COMMIT_HASH: $COMMIT_HASH"
+
+          if [ -f FILE_PATH ]; then
+            echo "PREV_PACKAGE_JSON=$FILE_PATH" >> $GITHUB_ENV
+            echo "FILE_PATH was found"
+          else 
+            echo "Error: FILE_PATH was not found"
+            exit 1
+          fi
+
+      - name: Compare package.json version
+        run: |
+          # 변수 작성
+
+          # 이전보다 버전 낮거나 동일하면 실패
